// <auto-generated />
using System;
using FileAnalisysService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileAnalisysService.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20250524121011_MakeWordAnalysisOwned")]
    partial class MakeWordAnalysisOwned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileAnalisysService.AnalyzedFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Similarities")
                        .HasColumnType("double precision");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FileAnalisysService.AnalyzedFile", b =>
                {
                    b.OwnsOne("FileAnalisysService.WordAnalysisResult", "WordAnalysis", b1 =>
                        {
                            b1.Property<Guid>("AnalyzedFileFileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CharacterCount")
                                .HasColumnType("integer");

                            b1.Property<int>("ParagraphCount")
                                .HasColumnType("integer");

                            b1.Property<int>("WordCount")
                                .HasColumnType("integer");

                            b1.HasKey("AnalyzedFileFileId");

                            b1.ToTable("Files");

                            b1.WithOwner()
                                .HasForeignKey("AnalyzedFileFileId");
                        });

                    b.Navigation("WordAnalysis")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
