version: '3.8'

services:
  # === PostgreSQL для FileStorage ===
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: filedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # === PostgreSQL для FileAnalysis ===
  analysis-postgres:
    image: postgres:15
    container_name: analysis-postgres
    environment:
      POSTGRES_DB: analysisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
    ports:
      - "5433:5432"
    volumes:
      - analysis_pg_data:/var/lib/postgresql/data

  # === File Storage API ===
  file-storage:
    build:
      context: ./FileStorage.Api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      ASPNETCORE_URLS: http://+:8001
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=filedb;Username=postgres;Password=mysecret
    depends_on:
      - postgres
    volumes:
      - file_data:/app/Files

  # === File Analysis API ===
  file-analysis:
    build:
      context: ./FileAnalysisService.Api
      dockerfile: Dockerfile
    container_name: file-analysis
    ports:
      - "8002:8002"
    environment:
      ASPNETCORE_URLS: http://+:8002
      ConnectionStrings__Default: Host=analysis-postgres;Port=5432;Database=analysisdb;Username=postgres;Password=mysecret
    depends_on:
      - analysis-postgres
    volumes:
      - wordcloud_data:/app/WordCloudImages

  # === API Gateway ===
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_URLS: http://+:8000
    depends_on:
      - file-storage
      - file-analysis

volumes:
  pg_data:
  analysis_pg_data:
  file_data:
  wordcloud_data:
