# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  api-gateway:
    build:
      context: "C:\\Users\\artba\\RiderProjects\\HSEPlagiat\\ApiGateway"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ApiGateway.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "apigateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\artba\\RiderProjects\\HSEPlagiat\\ApiGateway:/app:rw"
    - "C:\\Users\\artba\\RiderProjects\\HSEPlagiat:/src:rw"
    - "C:\\Users\\artba\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  file-analysis:
    build:
      context: "C:\\Users\\artba\\RiderProjects\\HSEPlagiat\\FileAnalysisService.Api"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/FileAnalysisService.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/FileAnalysisService.Api.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "fileanalysisservice.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\artba\\RiderProjects\\HSEPlagiat\\FileAnalysisService.Api:/app:rw"
    - "C:\\Users\\artba\\RiderProjects\\HSEPlagiat:/src:rw"
    - "C:\\Users\\artba\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  file-storage:
    build:
      context: "C:\\Users\\artba\\RiderProjects\\HSEPlagiat\\FileStorage.Api"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/FileStorage.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "filestorage.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\artba\\RiderProjects\\HSEPlagiat\\FileStorage.Api:/app:rw"
    - "C:\\Users\\artba\\RiderProjects\\HSEPlagiat:/src:rw"
    - "C:\\Users\\artba\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
